site_name: HPC-wiki
site_author: EarendelH
site_url: https://earendelh.github.io/hpc-wiki/
theme:
  name: material
  font:
    text: "Roboto"
    code: "Roboto Mono"
nav:
    - Home: index.md
    - linux:
      - tar: tar_tool.md
      - 检索集群信息: 检索集群信息.md
    - 集群使用记录:
      - 启明Qiming: 启明QiMing.md
      - Bridges-2: Bridges-2.md
      - Jetstream2: Jetstream2.md
      - Gadi: Gadi.md
    - 作业调度系统:
      - PBS: PBS.md
    - 相关论坛: 相关论坛.md
    - 比赛汇总及介绍: 比赛汇总及介绍.md
    - 高校超算集群指南: 高校超算集群指南.md
      
